#ifndef _HOME_TRIXTER_CLIONPROJECTS_GAMEPROJECTESC_INCLUDE_TREX_PlAYER_COMPONENT_H
#define _HOME_TRIXTER_CLIONPROJECTS_GAMEPROJECTESC_INCLUDE_TREX_PLAYER_COMPONENT_H

#include <lib/ecs/component.h>

class PlayerComponent : public IComponent {
    //тэг игрока
};
#endif // _HOME_TRIXTER_CLIONPROJECTS_GAMEPROJECTESC_INCLUDE_TREX_PLAYER_COMPONENT_H
